name: Test on Pull
run-name: ${{ github.actor }} committed to the repository

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '*'  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage  # Install coverage and any other dependencies

    - name: List directory contents
      run: ls -R

    - name: Run tests directly
      env:
        PYTHONPATH: ./src
      run: python -m unittest discover -s tests

    - name: Run tests with coverage
      env:
        PYTHONPATH: ./src
      run: coverage run -m unittest discover -s tests

    - name: Generate coverage report
      run: coverage report
