name: Test on Pull
run-name: ${{ github.actor }} committed to the repository

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '*'  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Compile the project
      run: mvn compile

    - name: Run tests
      run: mvn test

    - name: List directory contents
      run: ls -R

    - name: Run static analysis
      run: mvn checkstyle:check
